### PR TITLE
Add web-based emulators support

### PR DESCRIPTION
**Pull request by N1ark**
I don't know if the repo welcomes such additions, but might as well try it !

- Made the code run in non-windows environment, by moving imports of `winreg` and `win32gui` inside methods
- Added some methods to `Emulator`, allowing for more flexibility when running an emulator
- Add [Emmy](https://github.com/N1ark/gbc-emulator) emulator (I am the author of the emulator), using Selenium. Only one browser instance is opened, and ROMs are loaded for each test.

Although they're a minority, adding support for non-exe emulators could be a nice addition !

### CODE REVIEW

**Comment by daid** [comment]
Looks good, except that there now is an error in the CI run due to a hard dependency on the `selenium` package but that isn't installed in the CI job?

(I'm open to all kinds of additions if people are willing to put in the work, I just quickly hacked this together to see if it was possible)

**Comment by N1ark** [comment]
Cool, good to know ! Just fixed the error (hopefully)

**Comment by N1ark** [comment]
I'm [running the workflow on my branch](https://github.com/N1ark/GBEmulatorShootout/actions/runs/4024447918/jobs/6916487820) to see what's going wrong and I didn't get the error we had here - gonna look into it.

**Comment by N1ark** [comment]
Hmm I have no clue what's going wrong - [I tried the action](https://github.com/N1ark/GBEmulatorShootout/actions/runs/4032106408) on a separate branch of mine and it worked [and deployed](https://n1ark.github.io/GBEmulatorShootout/) fine (I had to do some minor changes for it to work but shouldn't be relevant). Have you encountered this error before?

**Comment by daid** [comment]
Don't remember seeing this one, but the whole thing is quite fragile and breaks quite often...

**Comment by N1ark** [comment]
The action failed because you didn't give enough permissions to the workflow apparently ?

**Pull request merged**
